"""add notes column to transactions

Revision ID: 3169222595d1
Revises: eaf9a6c10224
Create Date: 2026-07-04 18:04:30.696512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3169222595d1'
down_revision: Union[str, Sequence[str], None] = 'eaf9a6c10224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'notes')
    # ### end Alembic commands ###
